eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'api-pedido-pizzaria'
  data:
    mongodb:
      database: hackathon-pedido
      host: localhost
      port: 27017
      repositories:
        enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
